sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=Githubに出るメールアドレス
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=Githubに出るメールアドレス
    - secure: "aJpg/RLHSo/PPn4Nxk9NUJy0S2J3yc67OXVTqcdK+F4cLWTGj7OzHJA7ON7xm/LM5sUTo2zunLgNdC/AQO8QC4+MDMqcQkhIFVNrrKpIM8k80vDnvMR81rucmmshyaz2QARQc9nDKY1ujPc+xgORyXoAlQlF/i3rKqnEbGi0TsT7HfPxt6dG6XNcDRQisPgBdAS//CQ1G/sG2ARJs7+R0GcaTB7treKrn+DvfwGhIzC6JuVmV5YXyfOckv+ahR+G8oSPIpMfeJ+4qfHuYaQqy8ZW44rycs5Q+mqfPwmI5p3gI3ERNXjsxs6ymFdZpDjowQQFXKl3Tsrtv5paWglkLI2/5f1qWwIHPLZWtioSmnzEqQXV6EKIwhKYMgdhLRQ3rgQxXlXkEkvqXf5U6R7pEHnZdW4W2T5RvTtSmuH+cZjp6P8ygP9WcMicqYx9FVtk2GGCSxgHnR38RSrLRQBu3mhEJskTzogmCCmwDdKNoI6pgeiznx+qgOV7FrmKd/0JSp95vEjV/3xs1Suy/+dLKxzt3/nPJRvO8+WQUc0H9TxRkFmEOSx3el4XYt5p65xZWVay4qOTEtL0Fm5eKNYdRjAHksK30hCeOJuhy3BggOp1cRwzVRpg24/XEoacGP3lOMEaXGPpwhdFi5KfHQbmfK16GSS9Vor4ymJSlkyE+Ho="

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.3
      env: WP_VERSION=latest

before_script:
  - nvm install 6
  - npm install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi

after_success:
  - bash ./bin/deploy.sh
